version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-complaint
    environment:
      POSTGRES_USER: complaint_user
      POSTGRES_PASSWORD: StrongPassword572!%
      POSTGRES_DB: complaint_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local